### ISSUE TITLE
Here is the update for UE 4.25

### ISSUE THREAD

**Issue by wojciesh** [yar3333/text-to-speech-ue4#4]
Hi,
thanks for the plugin.
I've fixed issues occurring when loading it in UE 4.25.
Here is the working plugin:
https://illusionwa.re/tts-ue425/text-to-speech-ue4-master.zip

**Comment by yar3333** [comment]
Hello! I need a login/password to download your file :))

**Comment by wojciesh** [comment]
Sorry for that, it is without pass right now.

BTW. I've encountered a problem with the generated ProceduralSound - OnAudioFinished event won't fire (when played using AudioComponent or SpawnSoundAttached). I suppose there is some info missing. Could you suggest anything to fix it?

**Comment by yar3333** [comment]
I don't find good solution:  https://answers.unrealengine.com/questions/853460/view.html

**Comment by yar3333** [comment]
Thanks!
